Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace MovieApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieApp.Data;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(int? Id)
        {
            var movies = MovieRepository.Movies;
            if (Id!=null)
            {
                movies = movies.Where(x => x.CategoryId == Id).ToList();
            }
            return View(movies);
        }
        public IActionResult Detail(int Id)
        {
            return View(MovieRepository.GetMovieById(Id));
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent 
    {
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["action"].ToString()=="Index")
            {
                ViewBag.SelectedCategory = RouteData?.Values["id"];
            }
            return View(CategoryRepository.Categories);
        }
    }
}

Views/Home/Detail.cshtml
@model Movie

<div class="row">
    <div class="card mb-3">
        <div class="card-body">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <img src="~/img/@Model.ImageUrl" alt="@Model.Name" class="card-img" />
                </div>
                <div class="col-md-9 pl-2">
                    <h5 class="card-title">
                        @Model.Name
                    </h5>
                    <p class="card-text">@Html.Raw(Model.Description)</p>
                    <p class="card-text"><small class="text-muted">3 days ago</small></p>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@model IEnumerable<Movie>

    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryList")
        </div>
        <div class="col-md-9">
            <partial name="_Movies" />
        </div>
    </div>

Views/Shared/Components/CategoryList/Default.cshtml
@model IEnumerable<Category>
    <div class="list-group">
        <a href="/" class="list-group-item list-group-item-action">Tüm Kategoriler</a>
        @foreach (var item in Model)
        {
            <a asp-controller="Home" asp-action="Index" asp-route-id="@item.Id" class="list-group-item list-group-item-action @(ViewBag.SelectedCategory==item.Id.ToString()?"active": " ")">@item.Name</a>
        }
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
    </header>
    <div class="container">
        <main role="main" class="pb-3 pt-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MovieApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Movies.cshtml
@model IEnumerable<Movie>

@foreach (var item in Model)
{
    <div class="bd-example">
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="~/img/@item.ImageUrl" alt="@item.Name" class="card-img" />
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="/Home/Detail/@item.Id"> @item.Name</a>
                        </h5>
                        <p class="card-text">@item.ShortDescription</p>
                        <p class="card-text"><small class="text-muted">3 days ago</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="#">Movie App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
            </ul>
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>